spring.application.name=educalink


# Configuraci�n de la base de datos PostgreSQL
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci�n de Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilitar Swagger UI en Spring Boot
springdoc.swagger-ui.path=/swagger-ui.html