spring.application.name=educalink

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/educalinks
spring.datasource.username=postgres
spring.datasource.password=2608
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilitar Swagger UI en Spring Boot
springdoc.swagger-ui.path=/swagger-ui.html