spring.application.name=educalink

# Configuración de la base de datos PostgreSQL
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración Java Mail Sender
spring.mail.host=${HOST_MAIL}
spring.mail.port=${PORT_MAIL}
spring.mail.username=${USERNAME_MAIL}
spring.mail.password=${PASSWORD_MAIL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Habilitar Swagger UI en Spring Boot
springdoc.swagger-ui.path=/swagger-ui.html